on:
  push:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: | 
          ls -l 
          git status
          git log
          git fetch --prune --unshallow
          git for-each-ref refs/tags --sort=-taggerdate --count=1 --points-at=HEAD
