on:
  push:
    tags:
      - 'v*.*.*'
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: git version
        run: ls -l  \
              | git describe --tags $(git rev-list --tags --max-count=1)
